# Generated by Django 3.1 on 2020-08-14 17:32

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authenticate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherLicense', models.ImageField(null=True, upload_to='img')),
                ('teacherStatus', models.IntegerField(default=0)),
                ('studentLicense', models.ImageField(null=True, upload_to='img')),
                ('studentStatus', models.IntegerField(default=0)),
                ('idCard', models.ImageField(null=True, upload_to='img')),
                ('idStatus', models.IntegerField(default=0)),
                ('EnglishLevel', models.ImageField(null=True, upload_to='img')),
                ('EnglishStatus', models.IntegerField(default=0)),
                ('Else', models.ImageField(null=True, upload_to='img')),
                ('ElseStatus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='newModel.class')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belongClass', models.ManyToManyField(blank=True, related_name='belongClass', through='newModel.Relation', to='newModel.Class')),
            ],
            managers=[
                ('studentObj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            managers=[
                ('teacherObj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=15)),
                ('phoneNum', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=20)),
                ('passWord', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            managers=[
                ('userObj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.BooleanField(blank=True, default=True, null=True)),
                ('introduction', models.CharField(blank=True, max_length=50, null=True)),
                ('headSculpture', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('major', models.CharField(blank=True, max_length=20, null=True)),
                ('education', models.CharField(blank=True, max_length=20, null=True)),
                ('experience', models.CharField(blank=True, max_length=100, null=True)),
                ('VedioCenter', models.CharField(blank=True, max_length=50, null=True)),
                ('authenticate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newModel.authenticate')),
                ('relatedTeacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailInfo', to='newModel.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='newModel.user'),
        ),
        migrations.CreateModel(
            name='TargetGradeSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LEVEL', models.IntegerField(blank=True, null=True)),
                ('GradeStart', models.IntegerField(blank=True, null=True)),
                ('GradeEnd', models.IntegerField(blank=True, null=True)),
                ('SubjectsData', models.CharField(default='', max_length=40)),
                ('relatedTeacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='newModel.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.BooleanField(blank=True, default=True, null=True)),
                ('introduction', models.CharField(blank=True, max_length=50, null=True)),
                ('headSculpture', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('isNeedTeacher', models.BooleanField(blank=True, default=True, null=True)),
                ('NeedWhatTeacher', models.CharField(blank=True, max_length=50, null=True)),
                ('relatedStudent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailInfo', to='newModel.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='newModel.user'),
        ),
        migrations.AddField(
            model_name='relation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='newModel.student'),
        ),
        migrations.CreateModel(
            name='FilePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=50)),
                ('path', models.CharField(db_column='path', max_length=200)),
                ('isDelete', models.BooleanField(default=False)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('belong_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belong_class', to='newModel.class')),
            ],
            managers=[
                ('fpObj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_column='text', max_length=200)),
                ('isDelete', models.BooleanField(default=False)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='newModel.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='newModel.user')),
            ],
            managers=[
                ('converObj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='newModel.teacher'),
        ),
    ]
