# Generated by Django 3.1 on 2020-08-16 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newModel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherdetail',
            name='authenticate',
        ),
        migrations.AddField(
            model_name='teacher',
            name='authenticate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newModel.authenticate'),
        ),
    ]
